//handling the api request
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAIL = "API_REQUEST_FAIL";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const LOADING = "LOADING";
//message for  the alert
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";
//handling the authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//handling the main Slider
export const MAIN_SLIDER_CREATE_FAIL="MAIN_SLIDER_CREATE_FAIL"
export const MAIN_SLIDER_CREATE_SUCCESS="MAIN_SLIDER_CREATE_SUCCESS"
export const GET_MAIN_SLIDER_SUCCESS="GET_MAIN_SLIDER_SUCCESS"
export const GET_MAIN_SLIDER_FAIL="GET_MAIN_SLIDER_FAIL"
export const MAIN_SLIDER_DELETED_SUCCESS="MAIN_SLIDER_DELETED_SUCCESS"
export const MAIN_SLIDER_DELETED_FAIL="MAIN_SLIDER_DELETED_FAIL"
export const MAIN_SLIDER_EDIT_SUCCESS="MAIN_SLIDER_EDIT_SUCCESS"
export const MAIN_SLIDER_EDIT_FAIL="MAIN_SLIDER_EDIT_FAIL"